# Generated by Django 5.2.3 on 2025-07-03 20:06

import usuarios.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_paciente_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='paciente',
            managers=[
                ('objects', usuarios.managers.PacienteManager()),
            ],
        ),
    ]
