version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend-saludplus
      dockerfile: backend.Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend-saludplus:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.backend
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend-saludplus
      dockerfile: frontend.Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend-saludplus:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_started

volumes:
  postgres_data: